/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ConversationConversationIdRouteImport } from './routes/conversation.$conversationId'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedInboxConversationConversationIdRouteImport } from './routes/_authenticated/inbox/conversation.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConversationConversationIdRoute =
  ConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedInboxConversationConversationIdRoute =
  AuthenticatedInboxConversationConversationIdRouteImport.update({
    id: '/conversation/$conversationId',
    path: '/conversation/$conversationId',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/inbox/conversation/$conversationId': typeof AuthenticatedInboxConversationConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/inbox/conversation/$conversationId': typeof AuthenticatedInboxConversationConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/conversation/$conversationId': typeof ConversationConversationIdRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/inbox/conversation/$conversationId': typeof AuthenticatedInboxConversationConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/conversation/$conversationId'
    | '/inbox/'
    | '/inbox/conversation/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/profile'
    | '/settings'
    | '/conversation/$conversationId'
    | '/inbox'
    | '/inbox/conversation/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$username'
    | '/_authenticated/inbox'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/conversation/$conversationId'
    | '/_authenticated/inbox/'
    | '/_authenticated/inbox/conversation/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  ConversationConversationIdRoute: typeof ConversationConversationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/conversation/$conversationId': {
      id: '/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/conversation/$conversationId'
      preLoaderRoute: typeof ConversationConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/inbox/conversation/$conversationId': {
      id: '/_authenticated/inbox/conversation/$conversationId'
      path: '/conversation/$conversationId'
      fullPath: '/inbox/conversation/$conversationId'
      preLoaderRoute: typeof AuthenticatedInboxConversationConversationIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedInboxConversationConversationIdRoute: typeof AuthenticatedInboxConversationConversationIdRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedInboxConversationConversationIdRoute:
    AuthenticatedInboxConversationConversationIdRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  ConversationConversationIdRoute: ConversationConversationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
